LAB-node_attributes(), logdir, simple unit
Use LAB-node_attributes() to read node records. cd into a log
directory before exec'ing java. Read the log directory from
the 'logdir' setting. Change the type of zkbench.service systemd unit
from 'oneshot' to 'simple' (default).

diff --git a/caplab/zkbench b/caplab/zkbench
--- a/caplab/zkbench
+++ b/caplab/zkbench
@@ -32,16 +32,18 @@ set -u
 
 [[ $LAB_LOGLEVEL == trace ]] && set -o xtrace
 
-source $LAB_MODULES_ROOT/caplib/current/this.sh &&
-    source $LAB_MODULES_ROOT/caplib/current/cluster.sh &&
-    source $LAB_MODULES_ROOT/caplib/current/module.sh &&
+declare -r CAPLIB=$LAB_MODULES_ROOT/caplib/current
+
+source $CAPLIB/this.sh &&
+    source $CAPLIB/cluster.sh &&
+    source $CAPLIB/module.sh &&
+    source $CAPLIB/nodes.sh &&
     source $LAB_MODULES_ROOT/labconfig/current/config.sh || exit
 
 THIS_MODULE_ID=$(LAB-this_module) || exit
 THIS_MODULE_DIR="$LAB_MODULES_ROOT/$THIS_MODULE_ID"
-BENCHCONF=zkbench.conf
+BENCHCONF=$THIS_MODULE_DIR/zkbench.conf
 declare -r THIS_MODULE_ID THIS_MODULE_DIR BENCHCONF
-
 
 # Write a config for brownsys/zookeeper-benchmark to stdout. The benchmark
 # config contains the key=value pairs with the settings of this lab module
@@ -80,21 +82,20 @@ write_config() {
 	return 1
     }
 
-    awk -F ':[[:blank:]]+'\
-	'{ if ($2 && $1 != "target") printf "%s=%s\n", $1, $2 }'\
-	<<<"$settings"
-
-    local c iid t l ip h f s n rest   # node record fields
+    awk -F ':[[:blank:]]+' '{
+         if ($2 && $1 != "target" && $1 != "module") printf "%s=%s\n", $1, $2
+    }' <<<"$settings"
 
     local target_found=
-    while read -r c iid t l ip h f s n rest; do
-	[[ $c == $target ]] || continue
-	[[ $n =~ ^n([[:digit:]]+)$ ]] || {
-	    >&2 echo "ERROR: invalid node id '$n' for instance $iid in"\
-		"cluster $c"
+    declare -A node=([0]="$(LAB-node_attributes node)")
+    while read -r $node; do
+	[[ ${node[cluster]} == $target ]] || continue
+	[[ ${node[idx]} =~ ^n([[:digit:]]+)$ ]] || {
+	    >&2 echo "ERROR: invalid node id '${node[idx]}' for instance"\
+		"${node[iid]} in cluster ${node[cluster]}"
 	    return 1
 	}
-	echo "server.${BASH_REMATCH[1]}=$ip:2181"
+	echo "server.${BASH_REMATCH[1]}=${node[ip]}:2181"
 	target_found=1
     done <$LAB_CLUSTER_NODES
 
@@ -105,10 +106,15 @@ write_config() {
     }
 }
 
-cd $THIS_MODULE_DIR || exit
-
 LAB-file_uptodate $BENCHCONF || write_config >$BENCHCONF ||\
     { rm -f $BENCHCONF; exit 1; }
 
-exec java -cp lib/*:* edu.brown.cs.zkbenchmark.ZooKeeperBenchmark\
-     --conf $BENCHCONF
+logdir=$(awk -F = '{if ($1=="logdir") print $2}' $BENCHCONF)
+[[ $logdir ]] || {
+    >&2 echo "Log directory (logdir) setting is missing or invalid."
+    exit 1
+}
+
+cd $logdir &&
+    exec java -cp $THIS_MODULE_DIR/lib/*:$THIS_MODULE_DIR/*\
+	 edu.brown.cs.zkbenchmark.ZooKeeperBenchmark --conf $BENCHCONF
